#!/usr/bin/env node

if(process.argv.length < 6)
{
	console.info("\nHelp:\n");
	console.info("apns_test your_token development|production cert_key_path private_key_pem [Message]\n");
	return;
}
else if(process.argv[2].length!=64)
{
	console.error("Device Token must be 64 character");
	return;
}


var gateway ="";

if(process.argv[3]=="development") {
	
	gateway = "gateway.sandbox.push.apple.com";
}
else if(process.argv[3]=="production") {
	gateway ="gateway.push.apple.com";
}
else {
	console.error("only development or production is allow");
	return;
}



process.env.DEBUG="apn";

var apn = require('apn');



var options = { "gateway": gateway ,cert:process.argv[4],key:process.argv[5],connectionTimeout:1000};

var apnConnection = new apn.Connection(options);


var myDevice = new apn.Device(process.argv[2]);
var note = new apn.Notification();

note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge = 3;
note.sound = "ping.aiff";

var alertMessage = "Testing";

if(process.argv.length==7)
{
	alertMessage= process.argv[6];
}
note.alert = alertMessage;

note.payload = {'messageFrom': 'APNS TEST'};

apnConnection.pushNotification(note, myDevice);